# Page settings

baseurl = "."
languageCode = "en-us"
title = "Jin - Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Resume"
    author = "Jin Chan"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-4.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Jin Chan"
        tagline = "Software Engineer"
        avatar = ""

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:jin@virsyne.com"
        title = "jin@virsyne.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+60122918788"
        title = "+60122918788"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//virsyne.com"
        title = "virsyne.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/jinzen"
        title = "linkedin.com/in/jinzen"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/jin-virsyne"
        title = "github.com/jin-virsyne"

        #[[params.contact.list]]
        #class = "twitter"
        #icon = "fa-twitter"
        #url = "//twitter.com/username"
        #title = "@twittername"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc Hons Software Engineering"
        college = "Nottingham Trent University"
        dates = "2010 - 2013"

        [[params.education.list]]
        degree = "Diploma in Computer Studies"
        college = "NCC Education"
        dates = "2009 - 2010"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Mandarin"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "Malay"
        level = "Competent"

        [[params.language.list]]
        language = "Cantonese"
        level = "Conversational"

        [[params.language.list]]
        language = "Hakka"
        level = "Conversational"

    # Interests section
    #[params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Snowboarding"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Adaptable professional rejoining the job market after upskilling in Kubernetes, DevOps, AWS/GCE, and other technologies. Enthusiastic about diving into AI/ML projects and contributing to the next-gen software revolution."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Regional Analyst Programmer"
        dates = "Feb 2019 - Aug 2019"
        company = "Warner Music, Kuala Lumpur"
        details = """
- UI/UX Developer adept at translating system requirements into Sketch software prototypes.
- Executed frontend development for APAC region projects, aligning with approved prototypes and backend requirements.
- Collaborated within a diverse global team, comprising members from India, Japan, and the US."""

        [[params.jobs.list]]
        position = "Web Developer"
        dates = "Feb 2019 - Jan 2019"
        company = "Appstream, Selangor"
        details = """
- Spearheaded GUI revitalization or implementation for existing and new websites, enhancing user experience.
- Designed and developed dynamic frontend web pages.
- Single-handedly engineered a comprehensive property rental management system, encompassing frontend, backend, and database architecture."""

        [[params.jobs.list]]
        position = "Software Engineer"
        dates = "Aug 2013 - Sep 2016"
        company = "Datasonic Smart Solutions, Putrajaya"
        details = """
- Designed GUI and implemented frontend templates for diverse systems, primarily utilizing ASP .NET MVC, while also contributing to WPF and Windows Form projects.
- Executed backend API development and database table implementation.
- Developed system report generation using Crystal Report.
- Contributed to manufacturing & inventory management projects for MyKad (Malaysian Identity Card) and Malaysian Passport."""

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "Previously involved side projects and various endeavors."

        [[params.projects.list]]
        title = "Arknights Toolbox"
        url = "https://github.com/jin-virsyne/arknights-toolbox"
        tagline = "A versatile toolbox that computes materials and optimal farming routes. Initially derived from [aktools](https://github.com/gneko/aktools) with the author's consent, I subsequently adapted it to cater to Arknights Global server."

        [[params.projects.list]]
        title = "Stardew Valley Mods"
        url = "#"
        tagline = "Created custom maps using Tiled; and developed unique NPCs (non-player character) by utilizing [SMAPI](https://smapi.io/) and crafting their sprites from scratch."

        [[params.projects.list]]
        title = "Kongbakpao"
        url = "https://kongbakpao.com/"
        tagline = "Managed and optimized its wiki structure for mobile games."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Angular"
        level = "45%"

        [[params.skills.list]]
        skill = "ASP .NET MVC"
        level = "65%"

        [[params.skills.list]]
        skill = "C#"
        level = "80%"

        [[params.skills.list]]
        skill = "Devops"
        level = "50%"

        [[params.skills.list]]
        skill = "Django"
        level = "55%"

        [[params.skills.list]]
        skill = "Docker"
        level = "50%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "95%"
                
        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "90%"

        [[params.skills.list]]
        skill = "Kubernetes"
        level = "50%"

        [[params.skills.list]]
        skill = "Litestar"
        level = "30%"

        [[params.skills.list]]
        skill = "Python"
        level = "70%"

        [[params.skills.list]]
        skill = "Sketch & Photoshop"
        level = "70%"

        [[params.skills.list]]
        skill = "SQL"
        level = "75%"        

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Virsyne"
