apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blockchain
  name: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      containers:
      - image: virsyne/blockchain
        name: blockchain
        command: ["sh", "-c", "python blockchain.py"]
        resources: {}
