apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: litestar
  name: litestar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litestar
  template:
    metadata:
      labels:
        app: litestar
    spec:
      containers:
      - image: virsyne/litestar
        name: litestar
        command: ["litestar run -H 0.0.0.0 -p 8000"]
        resources: {}
        env:
        - name: LITESTAR_PORT
          value: "8000"
