apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resume
  name: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - image: ghcr.io/jin-virsyne/homework/resume:main
        name: resume
        resources: {}